### ISSUE TITLE
Build Yuzu with QtWebEngine?

### ISSUE THREAD

**Issue by oblitum** [linux-gamers/arch-yuzu-mainline#1]
Hi, really thanks for this awesome package, it makes things so much simpler. I want to make a request though, it would be really nice if it was built with `-DYUZU_USE_QT_WEB_ENGINE=ON` passed to cmake, otherwise there's no support for game manuals, etc, ingame.

**Comment by oblitum** [comment]
Then the AUR package would also need an update on the new dependency.

**Comment by linux-gamers** [comment]
Hi @oblitum , sorry for the late reply. We are going to test this flag on our CI build. If it is ok, we are going to add it as soon as possible. Thanks for letting us know about it.

**Comment by linux-gamers** [comment]
@oblitum the latest release (0.374-1) was compiled with the flag mentioned, and the **qt5-webengine** dependency was added to the AUR package. Could you give us a feedback if it working on your end ?

**Comment by oblitum** [comment]
Just tested and on Mario the Action Guide is now working, thanks.
